//! K2Node (Blueprint graph node) native trailing-data deserializer.
//!
//! # What's in the "trailing native data"?
//!
//! A Blueprint graph node (`UK2Node_*`) export in a `.uasset` is written in two parts:
//!
//! 1. **Tagged properties** — every `UPROPERTY()` on the node class. This covers
//!    `NodePosX/Y`, `NodeGuid`, `FunctionReference`, `VariableReference`, `EventReference`,
//!    `NodeComment`, etc. These are parsed by the existing tagged-property pipeline.
//! 2. **Native trailing data** — everything written by explicit `Serialize(FArchive&)`
//!    overrides *after* `Super::Serialize`. For UE 5.7 `UK2Node`, that is exactly the
//!    pins array (`UEdGraphNode::Serialize` appends `SerializeAsOwningNode(Ar, Pins)`).
//!
//! So this module's job is: given the trailing bytes of a `UK2Node_*` export, decode
//! the `TArray<UEdGraphPin*>` that lives there. Node-type-specific semantic info (the
//! function being called, the variable being got/set, etc.) already comes through as
//! tagged-property diffs in `uasset_diff.rs`.
//!
//! # Binary layout (UE 5.7, uncooked .uasset — editor-only data IS present)
//!
//! ```text
//! TArray<UEdGraphPin*>:
//!   ArrayNum: i32
//!   for each entry:
//!     bNullPtr: u32 (UE bool)
//!     if !bNullPtr:
//!       OwningNode: FPackageIndex (i32)
//!       PinId:      FGuid (4 × u32)
//!       [pin body — see below, only written for OwningNode-owned entries]
//!
//! UEdGraphPin body (OwningNode-typed array only — the outer Pins array):
//!   PinName:              FName (2 × u32)
//!   PinFriendlyName:      FText             ← editor-only
//!   SourceIndex:          i32               ← FUE5MainStreamObjectVersion::EdGraphPinSourceIndex
//!   PinToolTip:           FString
//!   Direction:            u8 (enum)
//!   PinType:              FEdGraphPinType   (see below)
//!   DefaultValue:         FString
//!   AutogeneratedDefault: FString
//!   DefaultObject:        FPackageIndex (i32)
//!   DefaultTextValue:     FText
//!   LinkedTo:             TArray<UEdGraphPin*>       (LinkedTo resolve-type — header only per entry)
//!   SubPins:              TArray<UEdGraphPin*>       (SubPins resolve-type — header only per entry)
//!   ParentPin:            UEdGraphPin*               (reference only)
//!   RefPassThrough:       UEdGraphPin*               (reference only)
//!   PersistentGuid:       FGuid                      ← editor-only
//!   BitField:             u32                         ← editor-only flags
//!
//! FEdGraphPinType:
//!   PinCategory:                 FName
//!   PinSubCategory:              FName
//!   PinSubCategoryObject:        FPackageIndex (i32)
//!   ContainerType:               u8
//!   PinValueType:                FEdGraphTerminalType  (only if ContainerType == Map)
//!   PinSubCategoryMemberRef:     FSimpleMemberReference (FPackageIndex + FName + FGuid)
//!   bIsReference:                u32 (bool)
//!   bIsWeakPointer:              u32 (bool)
//!   bIsConst:                    u32 (bool)
//!   bIsUObjectWrapper:           u32 (bool)
//!   bSerializeAsSinglePrecision: u32 (bool)   ← FUE5ReleaseStreamObjectVersion::SerializeFloatPinDefaultValuesAsSinglePrecision
//!
//! FEdGraphTerminalType:
//!   TerminalCategory:            FName
//!   TerminalSubCategory:         FName
//!   TerminalSubCategoryObject:   FPackageIndex (i32)
//!   bTerminalIsConst:            u32 (bool)
//!   bTerminalIsWeakPointer:      u32 (bool)
//!   bTerminalIsUObjectWrapper:   u32 (bool)
//!
//! FText (empty or Base history, the only two shapes we tolerate):
//!   Flags:       i32
//!   HistoryType: i8
//!     HistoryType == -1 (None):
//!       bHasCultureInvariantString: u32 (bool)
//!       CultureInvariantString:     FString (only if bool above)
//!     HistoryType == 0 (Base):
//!       Namespace:    FString
//!       Key:          FString
//!       SourceString: FString
//!     any other HistoryType: we bail to Unknown — the format is complex.
//! ```
//!
//! # LinkedTo / SubPins entries
//!
//! Inside a LinkedTo/SubPins/ParentPin/ReferencePassThroughConnection slot, a pin is
//! written as a *reference*, not as a full body. `SerializePin` writes:
//!   bNullPtr (u32 bool), and if not null: OwningNode (FPackageIndex) + PinId (FGuid).
//! We never recurse into the body for these — resolution happens in memory at load time.
//!
//! # Failure policy
//!
//! Any short read or unsupported variant → return `K2NodeData::Unknown` with the raw
//! bytes attached. The caller (diff engine) falls back to the existing
//! "native data changed (X → Y bytes)" message. **No panics, no Err bubble-up.**

use std::io::{self, Cursor, Read};

/// Parsed pin list from a K2Node's trailing native data, or Unknown on any parse failure.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum K2NodeData {
    Parsed { pins: Vec<Pin> },
    Unknown { raw: Vec<u8> },
}

/// A single pin inside a K2Node's Pins array, with best-effort decoded fields.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Pin {
    /// Stable identifier — used to match pins across old/new sides.
    pub pin_id: [u8; 16],
    pub pin_name: String,
    pub tooltip: String,
    /// 0 = input, 1 = output.
    pub direction: u8,
    pub pin_category: String,
    pub pin_sub_category: String,
    /// Container type: 0=None 1=Array 2=Set 3=Map.
    pub container_type: u8,
    pub is_reference: bool,
    pub is_const: bool,
    pub default_value: String,
    pub autogenerated_default: String,
    /// Package index of the default UObject (0 = null).
    pub default_object: i32,
    /// Pins this pin is connected to.
    pub linked_to: Vec<PinRef>,
    /// Sub-pins (for split struct pins).
    pub sub_pins: Vec<PinRef>,
    pub parent_pin: Option<PinRef>,
}

/// A soft reference to another pin — used inside LinkedTo/SubPins/ParentPin slots.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PinRef {
    /// Package index of the owning node (positive → export+1, negative → import−1, 0 → null).
    pub owning_node: i32,
    pub pin_id: [u8; 16],
}

/// Parse a K2Node's trailing native data into a pin list.
///
/// `data` must be exactly the trailing native bytes after the tagged-property
/// `None` terminator; `name_table` is the package name table for FName resolution.
pub fn parse_k2_node(data: &[u8], name_table: &[String]) -> K2NodeData {
    let mut r = Reader::new(data);
    match parse_pin_array_owning(&mut r, name_table) {
        Ok(pins) => K2NodeData::Parsed { pins },
        Err(_) => K2NodeData::Unknown { raw: data.to_vec() },
    }
}

// ===================================================================
// Reader — fallible, never panics.
// ===================================================================

struct Reader<'a> {
    cur: Cursor<&'a [u8]>,
}

impl<'a> Reader<'a> {
    fn new(data: &'a [u8]) -> Self {
        Self { cur: Cursor::new(data) }
    }

    fn read_exact(&mut self, buf: &mut [u8]) -> io::Result<()> {
        self.cur.read_exact(buf)
    }

    fn u8(&mut self) -> io::Result<u8> {
        let mut b = [0u8; 1];
        self.read_exact(&mut b)?;
        Ok(b[0])
    }

    fn i8(&mut self) -> io::Result<i8> {
        Ok(self.u8()? as i8)
    }

    fn i32(&mut self) -> io::Result<i32> {
        let mut b = [0u8; 4];
        self.read_exact(&mut b)?;
        Ok(i32::from_le_bytes(b))
    }

    fn u32(&mut self) -> io::Result<u32> {
        let mut b = [0u8; 4];
        self.read_exact(&mut b)?;
        Ok(u32::from_le_bytes(b))
    }

    /// UE bool serializes as uint32 — non-zero = true.
    fn bool32(&mut self) -> io::Result<bool> {
        Ok(self.u32()? != 0)
    }

    fn guid(&mut self) -> io::Result<[u8; 16]> {
        let mut b = [0u8; 16];
        self.read_exact(&mut b)?;
        Ok(b)
    }

    /// FString: i32 length. length > 0 → ASCII/UTF-8 bytes (null-terminated).
    /// length < 0 → UTF-16LE, |length| u16 code units (null-terminated). 0 → empty.
    fn fstring(&mut self) -> io::Result<String> {
        let len = self.i32()?;
        if len == 0 {
            return Ok(String::new());
        }
        if len > 0 {
            let n = len as usize;
            if n > 1 << 24 {
                return Err(io::Error::other("fstring too long"));
            }
            let mut buf = vec![0u8; n];
            self.read_exact(&mut buf)?;
            // Drop trailing null terminator if present.
            if buf.last() == Some(&0) {
                buf.pop();
            }
            Ok(String::from_utf8_lossy(&buf).into_owned())
        } else {
            let n = (-(len as i64)) as usize;
            if n > 1 << 24 {
                return Err(io::Error::other("fstring too long"));
            }
            let mut buf = vec![0u8; n * 2];
            self.read_exact(&mut buf)?;
            let mut u16s: Vec<u16> = buf
                .chunks_exact(2)
                .map(|c| u16::from_le_bytes([c[0], c[1]]))
                .collect();
            if u16s.last() == Some(&0) {
                u16s.pop();
            }
            Ok(String::from_utf16_lossy(&u16s))
        }
    }

    /// FName in package archive: name-index (i32) + number (i32).
    fn fname(&mut self, names: &[String]) -> io::Result<String> {
        let idx = self.i32()?;
        let number = self.i32()?;
        if idx < 0 || (idx as usize) >= names.len() {
            return Err(io::Error::other("fname idx out of range"));
        }
        let base = &names[idx as usize];
        if number > 0 {
            Ok(format!("{}_{}", base, number - 1))
        } else {
            Ok(base.clone())
        }
    }

    /// Skip an FText. Best-effort: handles None and Base history only.
    fn skip_ftext(&mut self) -> io::Result<()> {
        let _flags = self.i32()?;
        let hist = self.i8()?;
        match hist {
            -1 => {
                // None history: bHasCultureInvariantString + optional FString.
                let has_inv = self.bool32()?;
                if has_inv {
                    let _ = self.fstring()?;
                }
                Ok(())
            }
            0 => {
                // Base history: Namespace, Key, SourceString.
                let _ = self.fstring()?;
                let _ = self.fstring()?;
                let _ = self.fstring()?;
                Ok(())
            }
            _ => Err(io::Error::other("unsupported FText history")),
        }
    }
}

// ===================================================================
// Pin array + pin body parsing.
// ===================================================================

/// Parse the outer Pins array where each entry gets a full pin body.
fn parse_pin_array_owning(r: &mut Reader, names: &[String]) -> io::Result<Vec<Pin>> {
    let count = r.i32()?;
    if count < 0 || count > 65_536 {
        return Err(io::Error::other("pin count out of range"));
    }
    let mut pins = Vec::with_capacity(count as usize);
    for _ in 0..count {
        let b_null = r.bool32()?;
        if b_null {
            continue;
        }
        // SerializePin header (owning): LocalOwningNode + PinGuid, then body.
        let _owning_node = r.i32()?;
        let pin_id = r.guid()?;
        let pin = parse_pin_body(r, names, pin_id)?;
        pins.push(pin);
    }
    Ok(pins)
}

/// Parse a reference-only pin array (LinkedTo, SubPins).
fn parse_pin_array_refs(r: &mut Reader) -> io::Result<Vec<PinRef>> {
    let count = r.i32()?;
    if count < 0 || count > 65_536 {
        return Err(io::Error::other("ref array count out of range"));
    }
    let mut refs = Vec::with_capacity(count as usize);
    for _ in 0..count {
        if let Some(pref) = parse_pin_ref_slot(r)? {
            refs.push(pref);
        }
    }
    Ok(refs)
}

/// Parse a single optional pin reference slot (ParentPin, ReferencePassThrough, or one LinkedTo entry).
fn parse_pin_ref_slot(r: &mut Reader) -> io::Result<Option<PinRef>> {
    let b_null = r.bool32()?;
    if b_null {
        return Ok(None);
    }
    let owning_node = r.i32()?;
    let pin_id = r.guid()?;
    Ok(Some(PinRef { owning_node, pin_id }))
}

fn parse_pin_body(r: &mut Reader, names: &[String], pin_id: [u8; 16]) -> io::Result<Pin> {
    // PinName (UE 5.7: always FName since FFrameworkObjectVersion::PinsStoreFName).
    let pin_name = r.fname(names)?;

    // PinFriendlyName — editor-only FText.
    r.skip_ftext()?;

    // SourceIndex (UE 5.1+ — FUE5MainStreamObjectVersion::EdGraphPinSourceIndex).
    let _source_index = r.i32()?;

    let tooltip = r.fstring()?;
    let direction = r.u8()?;

    // PinType.
    let (pin_category, pin_sub_category, container_type, is_reference, is_const) =
        parse_pin_type(r, names)?;

    let default_value = r.fstring()?;
    let autogenerated_default = r.fstring()?;
    let default_object = r.i32()?;

    // DefaultTextValue.
    r.skip_ftext()?;

    let linked_to = parse_pin_array_refs(r)?;
    let sub_pins = parse_pin_array_refs(r)?;
    let parent_pin = parse_pin_ref_slot(r)?;
    let _ref_pass_through = parse_pin_ref_slot(r)?;

    // Editor-only: PersistentGuid + BitField.
    let _persistent_guid = r.guid()?;
    let _bit_field = r.u32()?;

    Ok(Pin {
        pin_id,
        pin_name,
        tooltip,
        direction,
        pin_category,
        pin_sub_category,
        container_type,
        is_reference,
        is_const,
        default_value,
        autogenerated_default,
        default_object,
        linked_to,
        sub_pins,
        parent_pin,
    })
}

/// Returns (category, sub_category, container_type, is_reference, is_const).
fn parse_pin_type(
    r: &mut Reader,
    names: &[String],
) -> io::Result<(String, String, u8, bool, bool)> {
    let category = r.fname(names)?;
    let sub_category = r.fname(names)?;
    let _sub_category_object = r.i32()?; // FPackageIndex
    let container_type = r.u8()?;
    if container_type == 3 {
        // Map — read FEdGraphTerminalType PinValueType.
        skip_terminal_type(r, names)?;
    }

    // PinSubCategoryMemberReference: FSimpleMemberReference { MemberParent: ObjectPtr, MemberName: FName, MemberGuid: FGuid }.
    let _member_parent = r.i32()?;
    let _member_name = r.fname(names)?;
    let _member_guid = r.guid()?;

    let is_reference = r.bool32()?;
    let _is_weak_pointer = r.bool32()?;
    let is_const = r.bool32()?;
    let _is_uobject_wrapper = r.bool32()?;
    // FUE5ReleaseStreamObjectVersion::SerializeFloatPinDefaultValuesAsSinglePrecision
    let _single_precision = r.bool32()?;

    Ok((category, sub_category, container_type, is_reference, is_const))
}

fn skip_terminal_type(r: &mut Reader, names: &[String]) -> io::Result<()> {
    let _terminal_category = r.fname(names)?;
    let _terminal_sub_category = r.fname(names)?;
    let _terminal_sub_category_object = r.i32()?;
    let _t_is_const = r.bool32()?;
    let _t_is_weak_pointer = r.bool32()?;
    let _t_is_uobject_wrapper = r.bool32()?;
    Ok(())
}

// ===================================================================
// Tests
// ===================================================================

#[cfg(test)]
mod tests {
    use super::*;

    /// Empty pins TArray — ArrayNum = 0 → should parse to zero pins.
    #[test]
    fn parses_empty_pin_array() {
        let data = [0u8, 0, 0, 0]; // i32 = 0
        let result = parse_k2_node(&data, &[]);
        assert!(matches!(result, K2NodeData::Parsed { pins } if pins.is_empty()));
    }

    /// Short/garbage input should never panic and should return Unknown.
    #[test]
    fn garbage_input_returns_unknown() {
        let data = [0xFFu8, 0xFF, 0xFF, 0x7F]; // huge positive count → over threshold
        let result = parse_k2_node(&data, &[]);
        assert!(matches!(result, K2NodeData::Unknown { .. }));
    }

    #[test]
    fn truncated_after_count_returns_unknown() {
        let data = [1u8, 0, 0, 0]; // 1 pin, but no body follows
        let result = parse_k2_node(&data, &[]);
        assert!(matches!(result, K2NodeData::Unknown { .. }));
    }

    /// Array of a single null-pin slot — bNullPtr = 1 → should produce empty pin list (null entries dropped).
    #[test]
    fn null_pin_slot_is_dropped() {
        let mut data = Vec::new();
        data.extend_from_slice(&1i32.to_le_bytes()); // count
        data.extend_from_slice(&1u32.to_le_bytes()); // bNullPtr = true
        let result = parse_k2_node(&data, &[]);
        match result {
            K2NodeData::Parsed { pins } => assert!(pins.is_empty()),
            _ => panic!("expected parsed"),
        }
    }

    /// FString round-trip: length 5 = "hello\0".
    #[test]
    fn fstring_reads_ascii() {
        let mut data = Vec::new();
        data.extend_from_slice(&6i32.to_le_bytes());
        data.extend_from_slice(b"hello\0");
        let mut r = Reader::new(&data);
        assert_eq!(r.fstring().unwrap(), "hello");
    }

    /// Empty FText (None history, no invariant string) = 9 bytes.
    #[test]
    fn skip_ftext_empty() {
        let mut data = Vec::new();
        data.extend_from_slice(&0i32.to_le_bytes()); // flags
        data.push(0xFFu8); // HistoryType = -1 (None)
        data.extend_from_slice(&0u32.to_le_bytes()); // bHasCultureInvariantString = false
        let mut r = Reader::new(&data);
        r.skip_ftext().unwrap();
    }

    #[test]
    fn fname_out_of_range_errors() {
        let mut data = Vec::new();
        data.extend_from_slice(&99i32.to_le_bytes());
        data.extend_from_slice(&0i32.to_le_bytes());
        let mut r = Reader::new(&data);
        assert!(r.fname(&["only_one".to_string()]).is_err());
    }
}
