#ifndef FORGE_FFI_H
#define FORGE_FFI_H

#pragma once

/* Generated by cbindgen from forge-ffi — do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Status code returned via [`forge_error_t::code`]. Numeric values are
 * part of the ABI — never renumber; append only.
 */
typedef enum forge_status_t {
    FORGE_OK = 0,
    FORGE_ERR_IO = 1,
    FORGE_ERR_ARG = 2,
    FORGE_ERR_AUTH = 3,
    FORGE_ERR_NOT_FOUND = 4,
    FORGE_ERR_CONFLICT = 5,
    FORGE_ERR_NOT_A_WORKSPACE = 6,
    FORGE_ERR_INTERNAL = 99,
} forge_status_t;

/**
 * Opaque handle for an open workspace session. The Rust body lives
 * inside the `crate::session` module; C callers must only ever pass
 * the pointer around — never dereference.
 */
typedef struct forge_session_t {
    uint8_t _opaque[0];
} forge_session_t;

/**
 * Error out-parameter. The library allocates `message` when
 * populating this; the caller must pass the struct back through
 * [`forge_error_free`] when done.
 *
 * Zero-initialised is valid: `code = FORGE_OK`, `message = null`.
 */
typedef struct forge_error_t {
    enum forge_status_t code;
    /**
     * Null-terminated UTF-8 message, or `NULL` when there's nothing
     * to say beyond the code. Allocated by this library; free via
     * [`forge_error_free`].
     */
    char *message;
} forge_error_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Library version (Cargo's `CARGO_PKG_VERSION`). Returned as a static
 * NUL-terminated UTF-8 string — do **not** free.
 *
 * # Safety
 * The returned pointer is valid for the lifetime of the loaded library.
 */
const char *forge_version(void);

/**
 * Open a session rooted at `workspace_path`, walking up the tree to
 * find a `.forge` directory (same rules as `forge` CLI).
 *
 * On success returns a non-null [`forge_session_t`] pointer; the
 * caller must release it via [`forge_session_close`]. On failure
 * returns null and populates `*out_err` when non-null.
 *
 * # Safety
 * - `workspace_path` must be a valid NUL-terminated UTF-8 C string.
 * - `out_err`, when non-null, must point to a writable `forge_error_t`.
 */
struct forge_session_t *forge_session_open(const char *workspace_path,
                                           struct forge_error_t *out_err);

/**
 * Release a session. Safe to call with `NULL`. Double-free is
 * undefined behaviour (there's no refcount on the C side).
 *
 * # Safety
 * `session` must either be null or have been returned by
 * [`forge_session_open`] and not yet closed.
 */
void forge_session_close(struct forge_session_t *session);

/**
 * Release a `forge_error_t` populated by this library. Safe to call
 * with `NULL` or with a zero-initialised struct.
 *
 * Resets `code` to `FORGE_OK` and `message` to null so the caller
 * can reuse the struct for a follow-up call without leaking the
 * prior message.
 *
 * # Safety
 * `err`, when non-null, must point to a struct whose `message` field
 * was allocated by this library (or is null).
 */
void forge_error_free(struct forge_error_t *err);

/**
 * Release a `char*` returned by one of the op functions (e.g.
 * [`forge_status_json`]). Safe on NULL.
 *
 * # Safety
 * `s`, when non-null, must be a pointer returned by this library.
 */
void forge_string_free(char *s);

/**
 * Snapshot the working-tree state as a JSON document.
 *
 * Output shape:
 * ```json
 * {
 *   "workspace_root": "C:/proj",
 *   "head": {"kind":"branch","name":"main"} | {"kind":"detached","hash":"..."},
 *   "dirty": ["Content/Foo.uasset", ...]   // placeholder until 4b
 * }
 * ```
 *
 * Returns null on error; frees message via [`forge_error_free`].
 * Non-null success values must be released via [`forge_string_free`].
 *
 * # Safety
 * `session` must be a non-null pointer returned by
 * [`forge_session_open`]. `out_err`, when non-null, must point to a
 * writable `forge_error_t`.
 */
char *forge_status_json(struct forge_session_t *session, struct forge_error_t *out_err);

/**
 * Return a JSON document summarising the workspace: root path,
 * workspace_id (used to match lock records), default remote URL,
 * repo name, current branch (or detached hash), and user identity.
 *
 * Every field the UE plugin currently shells out to `forge` for is
 * packed into one call — the bridge uses this to populate the
 * `FForgeSourceControlProvider` fields at module init without ever
 * running a subprocess.
 *
 * JSON shape:
 * ```json
 * {
 *   "workspace_root": "...",
 *   "workspace_id": "uuid-...",
 *   "repo": "alice/game" | "",
 *   "remote_url": "https://..." | null,
 *   "head": {"kind":"branch","name":"main"} | {"kind":"detached","hash":"..."},
 *   "user": {"name":"alice","email":"alice@example.com"},
 *   "workflow": "lock" | "merge"
 * }
 * ```
 *
 * Returns null + populates `*out_err` on failure. Non-null success
 * must be freed via [`forge_string_free`].
 *
 * # Safety
 * `session` non-null; `out_err` nullable writable.
 */
char *forge_workspace_info_json(struct forge_session_t *session, struct forge_error_t *out_err);

/**
 * Return the current branch name as an owned string, or null when
 * the workspace is in a detached state. `out_err` carries a real
 * error only for failure modes (unreadable config, missing HEAD);
 * detached HEAD is not an error.
 *
 * # Safety
 * `session` non-null; `out_err` nullable writable. Success values
 * must be freed via [`forge_string_free`].
 */
char *forge_current_branch(struct forge_session_t *session, struct forge_error_t *out_err);

/**
 * Stage the given paths (JSON array of UTF-8 path strings). Paths
 * are resolved relative to the session's workspace root.
 *
 * Returns 0 on success, non-zero on failure. `out_err` carries the
 * detail. On the Phase-4 perf path this removes N CreateProcess
 * invocations per CheckIn.
 *
 * # Safety
 * `session` non-null; `paths_json` non-null NUL-terminated UTF-8 C
 * string parseable as a JSON array of strings; `out_err` nullable.
 */
int forge_add_paths(struct forge_session_t *session,
                    const char *paths_json,
                    struct forge_error_t *out_err);

/**
 * Commit the currently-staged index with `message`. Returns 0 on
 * success; non-zero populates `*out_err` with the failure.
 *
 * # Safety
 * `session` non-null; `message` non-null UTF-8 C string; `out_err` nullable.
 */
int forge_commit(struct forge_session_t *session,
                 const char *message,
                 struct forge_error_t *out_err);

/**
 * Push the current workspace to its default remote. `force` flips
 * the `--force` flag (the server still enforces lock gates + ACLs).
 *
 * # Safety
 * `session` non-null; `out_err` nullable.
 */
int forge_push(struct forge_session_t *session, int force, struct forge_error_t *out_err);

/**
 * Pull the current workspace's default branch from its default
 * remote.
 *
 * # Safety
 * `session` non-null; `out_err` nullable.
 */
int forge_pull(struct forge_session_t *session, struct forge_error_t *out_err);

/**
 * List the active locks on this workspace's default remote as a
 * JSON array. Each element is `{"path":..., "owner":..., "created_at":...}`.
 *
 * Returns null on error; populates `*out_err`. Success values must
 * be released via [`forge_string_free`].
 *
 * # Safety
 * - `session` must be non-null.
 * - `out_err`, when non-null, must point to a writable struct.
 */
char *forge_lock_list_json(struct forge_session_t *session, struct forge_error_t *out_err);

/**
 * Acquire a lock on `path` for the current workspace user.
 *
 * `reason` may be NULL for no reason. Returns 0 on success, non-zero
 * on failure (check `*out_err` for detail).
 *
 * # Safety
 * `session` non-null, `path` non-null UTF-8 C string, `reason`
 * nullable UTF-8 C string, `out_err` nullable writable pointer.
 */
int forge_lock_acquire(struct forge_session_t *session,
                       const char *path,
                       const char *reason,
                       struct forge_error_t *out_err);

/**
 * Release the caller's lock on `path`. No-op if no lock is held.
 * Returns 0 on success, non-zero on failure.
 *
 * # Safety
 * Same rules as [`forge_lock_acquire`] minus the `reason` arg.
 */
int forge_lock_release(struct forge_session_t *session,
                       const char *path,
                       struct forge_error_t *out_err);

int forge_abi_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* FORGE_FFI_H */
